/navsat_converter:
  ros__parameters:
    conv:
      gps:
        fix_topics:
          - /fix
      xyz:
        odometry_topics:
          - /odometry
        point_topics:
          - /point
        pose_topics:
          - /pose
        posecov_topics:
          - /pose_cov
    dua:
      tf_server:
        get_transform: true
        transform_pose: false
        wait_servers: false
    earth:
      frame: earth
      gps:
        lat: 41.854693
        lon: 12.624754
        alt: 72.0
      topic_stream: false
    target:
      frame: map
    tf:
      ignore_stamp: false
      timeout_ms: 100
    use_sim_time: false
